//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangFromTextWinApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangFromTextWinApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string T001 {
            get {
                return ResourceManager.GetString("T001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string T002 {
            get {
                return ResourceManager.GetString("T002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sentence.
        /// </summary>
        internal static string T003 {
            get {
                return ResourceManager.GetString("T003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string T005 {
            get {
                return ResourceManager.GetString("T005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string T006 {
            get {
                return ResourceManager.GetString("T006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string T007 {
            get {
                return ResourceManager.GetString("T007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string T008 {
            get {
                return ResourceManager.GetString("T008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LangFromtext is a desktop lang-trainer application based on your &quot;self-made&quot; database.
        ///You need more data. Please index web or text files and populate your text database..
        /// </summary>
        internal static string T009 {
            get {
                return ResourceManager.GetString("T009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicely, your database contains {0} words which is enough..
        /// </summary>
        internal static string T010 {
            get {
                return ResourceManager.GetString("T010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well, your database consists of {0} text sources ({1} text source per 1000 words)..
        /// </summary>
        internal static string T012 {
            get {
                return ResourceManager.GetString("T012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are only {0} text sources per 1000 words. Try to get more text sources from web or files..
        /// </summary>
        internal static string T013 {
            get {
                return ResourceManager.GetString("T013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start filling the database.
        /// </summary>
        internal static string T014 {
            get {
                return ResourceManager.GetString("T014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your database contains enough data and you can fully use application..
        /// </summary>
        internal static string T018 {
            get {
                return ResourceManager.GetString("T018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete text source &apos;{0}&apos;?.
        /// </summary>
        internal static string T019 {
            get {
                return ResourceManager.GetString("T019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string T020 {
            get {
                return ResourceManager.GetString("T020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score: {0}.
        /// </summary>
        internal static string T021 {
            get {
                return ResourceManager.GetString("T021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database File is probably corrupted. Application will try to create new database file. Please check Settings if you want to change current database..
        /// </summary>
        internal static string T022 {
            get {
                return ResourceManager.GetString("T022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan level.
        /// </summary>
        internal static string T023 {
            get {
                return ResourceManager.GetString("T023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only url that contains.
        /// </summary>
        internal static string T024 {
            get {
                return ResourceManager.GetString("T024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only url that not contains.
        /// </summary>
        internal static string T025 {
            get {
                return ResourceManager.GetString("T025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Name.
        /// </summary>
        internal static string T026 {
            get {
                return ResourceManager.GetString("T026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database folder.
        /// </summary>
        internal static string T027 {
            get {
                return ResourceManager.GetString("T027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create database.
        /// </summary>
        internal static string T028 {
            get {
                return ResourceManager.GetString("T028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHRASE.
        /// </summary>
        internal static string T029 {
            get {
                return ResourceManager.GetString("T029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEXT SOURCES.
        /// </summary>
        internal static string T030 {
            get {
                return ResourceManager.GetString("T030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIDE.
        /// </summary>
        internal static string T031 {
            get {
                return ResourceManager.GetString("T031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web indexer.
        /// </summary>
        internal static string T032 {
            get {
                return ResourceManager.GetString("T032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string T033 {
            get {
                return ResourceManager.GetString("T033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextSources.
        /// </summary>
        internal static string T034 {
            get {
                return ResourceManager.GetString("T034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string T035 {
            get {
                return ResourceManager.GetString("T035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search (Enter).
        /// </summary>
        internal static string T036 {
            get {
                return ResourceManager.GetString("T036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurrence.
        /// </summary>
        internal static string T037 {
            get {
                return ResourceManager.GetString("T037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Sources.
        /// </summary>
        internal static string T038 {
            get {
                return ResourceManager.GetString("T038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string T039 {
            get {
                return ResourceManager.GetString("T039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string T040 {
            get {
                return ResourceManager.GetString("T040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get text source from files.
        /// </summary>
        internal static string T041 {
            get {
                return ResourceManager.GetString("T041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show sentences.
        /// </summary>
        internal static string T042 {
            get {
                return ResourceManager.GetString("T042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase checker.
        /// </summary>
        internal static string T043 {
            get {
                return ResourceManager.GetString("T043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluate (Enter).
        /// </summary>
        internal static string T044 {
            get {
                return ResourceManager.GetString("T044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match.
        /// </summary>
        internal static string T045 {
            get {
                return ResourceManager.GetString("T045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phrase pattern.
        /// </summary>
        internal static string T046 {
            get {
                return ResourceManager.GetString("T046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Database.
        /// </summary>
        internal static string T047 {
            get {
                return ResourceManager.GetString("T047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change DB.
        /// </summary>
        internal static string T048 {
            get {
                return ResourceManager.GetString("T048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database.
        /// </summary>
        internal static string T049 {
            get {
                return ResourceManager.GetString("T049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic lang-trainer interval.
        /// </summary>
        internal static string T050 {
            get {
                return ResourceManager.GetString("T050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string T051 {
            get {
                return ResourceManager.GetString("T051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string T052 {
            get {
                return ResourceManager.GetString("T052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your database contains {0} words, you need at least {1} words..
        /// </summary>
        internal static string T053 {
            get {
                return ResourceManager.GetString("T053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic lang-trainer is enabled. You can turn it off in section .
        /// </summary>
        internal static string T054 {
            get {
                return ResourceManager.GetString("T054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic lang-trainer is disabled. You can turn it on in section.
        /// </summary>
        internal static string T055 {
            get {
                return ResourceManager.GetString("T055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Source Detail.
        /// </summary>
        internal static string T056 {
            get {
                return ResourceManager.GetString("T056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max limit.
        /// </summary>
        internal static string T057 {
            get {
                return ResourceManager.GetString("T057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get text source from web.
        /// </summary>
        internal static string T058 {
            get {
                return ResourceManager.GetString("T058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling....
        /// </summary>
        internal static string T059 {
            get {
                return ResourceManager.GetString("T059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel scan.
        /// </summary>
        internal static string T060 {
            get {
                return ResourceManager.GetString("T060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Language.
        /// </summary>
        internal static string T061 {
            get {
                return ResourceManager.GetString("T061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        internal static string T062 {
            get {
                return ResourceManager.GetString("T062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string T063 {
            get {
                return ResourceManager.GetString("T063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Theme.
        /// </summary>
        internal static string T064 {
            get {
                return ResourceManager.GetString("T064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string T065 {
            get {
                return ResourceManager.GetString("T065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} items?.
        /// </summary>
        internal static string T066 {
            get {
                return ResourceManager.GetString("T066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working... Please wait.
        /// </summary>
        internal static string T067 {
            get {
                return ResourceManager.GetString("T067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading database... Please wait.
        /// </summary>
        internal static string T068 {
            get {
                return ResourceManager.GetString("T068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File indexer: &apos;{0}&apos; files was successfully indexed..
        /// </summary>
        internal static string T069 {
            get {
                return ResourceManager.GetString("T069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s go.
        /// </summary>
        internal static string T070 {
            get {
                return ResourceManager.GetString("T070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe later.
        /// </summary>
        internal static string T071 {
            get {
                return ResourceManager.GetString("T071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s time for a quick lang-training....
        /// </summary>
        internal static string T072 {
            get {
                return ResourceManager.GetString("T072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start page.
        /// </summary>
        internal static string T073 {
            get {
                return ResourceManager.GetString("T073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang-games.
        /// </summary>
        internal static string T074 {
            get {
                return ResourceManager.GetString("T074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-start.
        /// </summary>
        internal static string T075 {
            get {
                return ResourceManager.GetString("T075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically launch app after the user login.
        /// </summary>
        internal static string T076 {
            get {
                return ResourceManager.GetString("T076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string T077 {
            get {
                return ResourceManager.GetString("T077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An open-source desktop lang-trainer application based on your self-made database.
        ///LangFromText is released under the GPLv3 (GNU GENERAL PUBLIC LICENSE)
        ///https://github.com/Jpinsoft/LangFromText
        ///
        ///
        ///LangFromText was made possible thanks to these excellent libraries:
        ///-------------------
        ///
        ///Font-Awesome-WPF/UWP
        ///Copyright (c) 2014-2016 charri
        ///The MIT License (MIT)
        ///https://github.com/charri/Font-Awesome-WPF/
        ///
        ///Json.NET
        ///Copyright (c) 2007 James Newton-King
        ///The MIT License (MIT)
        ///https://www.newtonsoft.co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string T078 {
            get {
                return ResourceManager.GetString("T078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize application. App will Close. .
        /// </summary>
        internal static string T079 {
            get {
                return ResourceManager.GetString("T079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LangFromText - Lang-trainer.
        /// </summary>
        internal static string T080 {
            get {
                return ResourceManager.GetString("T080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED: Start every {0} minutes.
        /// </summary>
        internal static string T081 {
            get {
                return ResourceManager.GetString("T081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start every {0} minutes.
        /// </summary>
        internal static string T082 {
            get {
                return ResourceManager.GetString("T082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart application to apply changes..
        /// </summary>
        internal static string T083 {
            get {
                return ResourceManager.GetString("T083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Please enter a valid URL address -----.
        /// </summary>
        internal static string T084 {
            get {
                return ResourceManager.GetString("T084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open LangFromText.
        /// </summary>
        internal static string T085 {
            get {
                return ResourceManager.GetString("T085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang-trainer - random game.
        /// </summary>
        internal static string T086 {
            get {
                return ResourceManager.GetString("T086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string T087 {
            get {
                return ResourceManager.GetString("T087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL template - open translator.
        /// </summary>
        internal static string T088 {
            get {
                return ResourceManager.GetString("T088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Translation.
        /// </summary>
        internal static string T089 {
            get {
                return ResourceManager.GetString("T089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset score data for this module?.
        /// </summary>
        internal static string T090 {
            get {
                return ResourceManager.GetString("T090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset score.
        /// </summary>
        internal static string T091 {
            get {
                return ResourceManager.GetString("T091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the word.
        /// </summary>
        internal static string T200 {
            get {
                return ResourceManager.GetString("T200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the correct phrase.
        /// </summary>
        internal static string T201 {
            get {
                return ResourceManager.GetString("T201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the correct word.
        /// </summary>
        internal static string T202 {
            get {
                return ResourceManager.GetString("T202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocabulary training.
        /// </summary>
        internal static string T203 {
            get {
                return ResourceManager.GetString("T203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough words. Try to get more text sources from web or files..
        /// </summary>
        internal static string T204 {
            get {
                return ResourceManager.GetString("T204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you know this word?.
        /// </summary>
        internal static string T205 {
            get {
                return ResourceManager.GetString("T205", resourceCulture);
            }
        }
    }
}
